### ISSUE TITLE
[9.0] Print BOM should show part number, part name and description

### ISSUE THREAD

**Issue by jbeficent** [OmniaSolutions/OdooPLM#2]
At this moment the part number does not appear in any of the options to print a BOM.

![image](https://cloud.githubusercontent.com/assets/7683926/23162454/5ff8118c-f82e-11e6-9a2f-d11d40437764.png)

**Comment by mboscolo** [comment]
Hi What do you mean with Part number not appear ?

do you mean on reports ?


regards

Matteo


*OmniaSolutions*
/*Matteo Boscolo*
Technical Manager/
Cell. +39.327.1525045
Fax. +39.041.8623730
tech@omniasolutions.eu
Skype: matteo.boscolo

**Comment by jbeficent** [comment]
@mboscolo yes, it does not appear in the reports.

cc @lreficent

**Comment by mboscolo** [comment]
It's the first row of the report.

regards,

Matteo


*OmniaSolutions*
/*Matteo Boscolo*
Technical Manager/
Cell. +39.327.1525045
Fax. +39.041.8623730
tech@omniasolutions.eu
Skype: matteo.boscolo

**Comment by jbeficent** [comment]
See the attached picture

![image](https://cloud.githubusercontent.com/assets/7683926/23260384/e3a773de-f9d1-11e6-810e-b5236df5e4dd.png)

It is missing the column for part number of the components.

**Comment by jbeficent** [comment]
Sorry, the part number shows, but not the part name.

**Comment by jbeficent** [comment]
The column 'Product name' should be replaced by 'Part number'
A new column 'Product name' should include the name of the product. See what field I refer to below.

![image](https://cloud.githubusercontent.com/assets/7683926/23260624/fb611ace-f9d2-11e6-831d-943838e44353.png)

**Comment by mboscolo** [comment]
it's as designed, because on our side the engineering_code is the unique 
name of it.

the report is a qweb one..

you can easily overload it :)


regards,

Matteo


*OmniaSolutions*
/*Matteo Boscolo*
Technical Manager/
Cell. +39.327.1525045
Fax. +39.041.8623730
tech@omniasolutions.eu
Skype: matteo.boscolo

**Comment by jbeficent** [comment]
Ok, will extend the qweb then.
